server:
  port: 8085

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable route discovery via Eureka
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 100
        waitDurationInOpenState: 1000
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 2

  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 100


